name: Run Notebooks

on:
  push:
    branches:
      - ci  # Change this to your repository's main branch
  pull_request:
    branches:
      - ci
  schedule:
      - cron: "0 0 * * 0"  # Run every Sunday at midnight UTC (4 week interval)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.6  # Use the Python version you need

    - name: Install dependencies
      run: pip install jupyter nbconvert
    - run: pip install -r requirements.txt   

    - name: Find notebooks
      id: find-notebooks
      run: |
        find . -name "*.ipynb" > notebooks.txt
        cat notebooks.txt
      shell: bash

    - name: Execute notebooks
      run: |
        cat notebooks.txt | while read -r notebook; do
          jupyter nbconvert --to notebook --execute --inplace "$notebook"
        done
      continue-on-error: true
      shell: bash

    - name: Check for errors
      run: |
        if grep "raise Exception(" *.ipynb; then
          echo "Error found in notebook(s)."
          exit 1
        else
          echo "No errors found in notebooks."
        fi
      shell: bash